name: SteveBrains
description: A new Flutter project.

version: 2.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  flutter_custom_clippers: ^0.1.6
  html_unescape: ^1.0.1+2
  auto_size_text: ^2.0.0+2
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  share: ^0.6.0+1
  fluttertoast: ^3.0.4
  avatar_glow: ^0.1.0
  bottom_navy_bar: ^3.0.0
  shared_preferences: ^0.5.2
  google_sign_in:
  connectivity:
  percent_indicator: ^2.1.1
  rxdart: ^0.21.0
  firebase_core:
  provider: 3.1.0
  charts_flutter: ^0.8.1
  cloud_firestore: 0.13.5
  theme_provider: ^0.3.3
  simple_animations: ^1.3.3
  font_awesome_flutter: ^8.8.1
  cached_network_image:
  flutter_svg: ^0.17.4
  flutter_spinkit: ^4.1.2+1
  firebase_admob: ^0.9.3+2
  url_launcher: ^5.4.10
  flutter_open_whatsapp: ^0.1.2
  firebase_auth:

  # screenshot_and_share: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: arial
      fonts:
        - asset: fonts/arial.ttf
          weight: 100
